PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO entities
  (id, entity_type, title, original_title, creator, year, research_status, notes)
VALUES
  ('rm', 'person', 'RM / Kim Namjoon', '김남준', NULL, 1994, 'published', 'Central subject of the archive.'),
  ('book-depth-of-the-landscape', 'book', 'The Depth of the Landscape', '풍경의 깊이', 'Kang Yobae', NULL, 'verified', 'Korean-language collection of Kang Yobae essays, paintings and reflections.'),
  ('book-honeybees-distant-thunder', 'book', 'Honeybees and Distant Thunder', '蜜蜂と遠雷', 'Riku Onda', 2016, 'verified', 'The Weverse article uses the romanized title Mitsubachi to Enrai.'),
  ('book-that-summers-end', 'book', 'That Summer’s End', '그 여름의 끝', 'Lee Seong-bok', 1990, 'verified', 'Poetry collection; also rendered as End of the Summer by Weverse.'),
  ('book-all-about-saul-leiter', 'book', 'All About Saul Leiter', NULL, 'Saul Leiter, Margit Erb, Pauline Vermare and Motoyuki Shibata', 2017, 'verified', 'First published in Japan by Seigensha.'),
  ('book-midnight-library', 'book', 'The Midnight Library', NULL, 'Matt Haig', 2020, 'verified', NULL),
  ('book-doing-good-better', 'book', 'Doing Good Better', NULL, 'William MacAskill', 2015, 'verified', NULL),
  ('artist-kang-yobae', 'artist', 'Kang Yobae', '강요배', NULL, 1952, 'verified', 'Korean painter whose work centers on Jeju’s nature, history and memory.'),
  ('artwork-kang-yobae-munnamu', 'artwork', 'Munnamu', '먼나무', 'Kang Yobae', 2020, 'verified', 'Acrylic on canvas, 162 × 112 cm; identified by Daegu Art Museum in its post about RM’s visit.'),
  ('exhibition-kang-yobae-carnation', 'exhibition', 'Kang Yobae: Carnation — When Mind Becomes Body', '강요배: 카네이션-마음이 몸이 될 때', 'Daegu Art Museum', 2021, 'verified', '21st Lee In-sung Art Award exhibition, 2021-10-13 through 2022-01-09.'),
  ('museum-daegu-art-museum', 'museum', 'Daegu Art Museum', '대구미술관', NULL, 2011, 'verified', NULL);

INSERT OR IGNORE INTO sources
  (id, title, publisher, url, source_class, authority_rank, published_at, accessed_at, access_notes)
VALUES
  ('src-weverse-bibilly-hills', 'RM’s Bibilly Hills', 'Weverse Magazine', 'https://magazine.weverse.io/article/view/632?artist=BTS&lang=en', 'official_content', 2, '2023-01-09', '2026-08-10', 'The Reading section lists six books RM had recently mentioned. It does not label each one as a recommendation.'),
  ('src-weverse-in-the-soop2-guide', 'In the SOOP BTS ver. Season2 global paid content user guide', 'Weverse', 'https://weverse.io/bts/notice/1720', 'official_content', 2, '2021-09-23', '2026-08-10', 'Confirms the official programme and episode release structure, but not a specific book or timestamp.'),
  ('src-namjoons-booklist', 'Namjoon’s Booklist', 'Namjoon’s Booklist', 'https://namjoonsbooklist.com/', 'community_archive', 4, NULL, '2026-08-10', 'Use as a lead index. Promote a claim only after checking the cited primary material.'),
  ('src-hanbooks-depth-landscape', 'The Depth of the Landscape', 'HanBooks', 'https://www.hanbooks.com/deofla.html', 'reputable_secondary', 3, NULL, '2026-08-10', 'Bibliographic context: Korean title, author, publisher and ISBN.'),
  ('src-penguin-honeybees-sample', 'Honeybees and Distant Thunder sample', 'Penguin Random House UK', 'https://cdn.penguin.co.uk/dam-assets/books/9780857527950/9780857527950-sample.pdf', 'institutional_record', 2, NULL, '2026-08-10', 'Bibliographic context for the English edition and original Japanese title.'),
  ('src-hankyung-that-summers-end', 'The book BTS RM reads at the end of summer', 'The Korea Economic Daily', 'https://www.hankyung.com/article/202209227766i', 'reputable_secondary', 3, '2022-09-22', '2026-08-10', 'Reports that RM posted the poetry collection cover to his Instagram Story on 2022-09-21.'),
  ('src-thames-all-about-saul-leiter', 'All About Saul Leiter', 'Thames & Hudson', 'https://www.thamesandhudson.com/products/all-about-saul-leiter', 'institutional_record', 2, NULL, '2026-08-10', 'Publisher metadata and contributors.'),
  ('src-prh-midnight-library', 'The Midnight Library', 'Penguin Random House', 'https://www.penguinrandomhouse.com/books/575653/the-midnight-library-by-matt-haig/', 'institutional_record', 2, NULL, '2026-08-10', 'Publisher metadata for the book.'),
  ('src-prh-doing-good-better', 'Doing Good Better', 'Penguin Random House', 'https://www.penguinrandomhouse.com/books/316786/doing-good-better-by-william-macaskill/', 'institutional_record', 2, NULL, '2026-08-10', 'Publisher metadata for the book.'),
  ('src-rkive-read-with-bts', 'read with bts rkive', 'to live, to love', 'https://rkivelibrary.wordpress.com/2023/01/25/read-with-bts-rkive/', 'community_archive', 4, '2023-01-25', '2026-08-10', 'Detailed fan research places the TBR mention in In the SOOP 2 episode 1 and RM starting the book in episode 3.'),
  ('src-reddit-its2-ep3', 'In the SOOP BTS ver. Season 2 — Episode 3 discussion', 'r/bangtan', 'https://www.reddit.com/r/bangtan/comments/qic9ls', 'community_archive', 4, '2021-10-29', '2026-08-10', 'Contemporaneous viewer discussion independently identifies RM reading The Midnight Library in episode 3.'),
  ('src-reddit-its2-ep4', 'In the SOOP BTS ver. Season 2 — Episode 4 discussion', 'r/bangtan', 'https://www.reddit.com/r/bangtan/comments/qnama0', 'community_archive', 4, '2021-11-05', '2026-08-10', 'Contemporaneous viewer discussion refers to RM sharing a quotation from The Midnight Library.'),
  ('src-reddit-its2-ep5', 'In the SOOP BTS ver. Season 2 — Episode 5 discussion', 'r/bangtan', 'https://www.reddit.com/r/bangtan/comments/qsanxa', 'community_archive', 4, '2021-11-12', '2026-08-10', 'Viewer discussion records repeated book exposure and raises an unverified product-placement concern.'),
  ('src-elcomercio-its2-ep3', 'What book did SUGA read and why did ARMY react?', 'El Comercio', 'https://elcomercio.pe/luces/musica/bts-que-libro-leyo-suga-y-por-que-army-se-emociono-al-conocer-el-titulo-suga-rapero-k-pop-grupo-musical-idol-tdex-noticia/', 'reputable_secondary', 3, '2021-11-24', '2026-08-10', 'Embeds a contemporary post identifying episode 3 footage of RM and SUGA reading.'),
  ('src-buro-midnight-library', 'Read like BTS’ RM: 7 Book recommendations by Kim Namjoon', 'BURO.', 'https://www.buro247.my/culture/read-like-bts-rm-book-recommendations-namjoon.html', 'reputable_secondary', 3, NULL, '2026-08-10', 'Says RM read the book and narrated a passage on In the SOOP; the article calls it season three, so its episode wording needs primary verification.'),
  ('src-gq-midnight-library', 'GQ Reads: 5 books recommended by RM', 'GQ India', 'https://www.gqindia.com/content/gq-reads-5-books-recommended-by-rm-that-flaunt-the-bts-leaders-lyrical-prowess', 'reputable_secondary', 3, NULL, '2026-08-10', 'Claims RM recommended The Midnight Library to V, but provides no episode timestamp or primary clip in the accessible article text.'),
  ('src-ameblo-midnight-library-highlight', 'In the SOOP 2: RM and The Midnight Library highlighted passage', 'Ameblo / moon-jin1992', 'https://ameblo.jp/moon-jin1992/entry-12710503871.html', 'community_archive', 4, NULL, '2026-08-10', 'Fan archive describes and reproduces the passage RM highlighted from The Midnight Library during In the SOOP 2. It supplies scene-level corroboration but no reliable episode timestamp.'),
  ('src-bts-twitter-20211005-green', 'Green: RM photo set with books and art', 'BTS official account / X', 'https://x.com/BTS_twt/status/1445397240118382592', 'official_content', 2, '2021-10-05', '2026-08-10', 'Primary public post. Photo 1 shows RM’s book area, but the caption does not name any book.'),
  ('src-vpl-namjoon-bookshelf', 'Namjoon’s Bookshelf', 'Vancouver Public Library', 'https://vpl.bibliocommons.com/v2/list/display/1338249780/1429564517', 'reputable_secondary', 3, NULL, '2026-08-10', 'Staff-curated library list identifies Doing Good Better in RM’s bookshelf photograph and dates the image to 2021-10-05; it incorrectly labels the platform as Weverse.'),
  ('src-reddit-rm-20211005', '211005 RM', 'r/bangtan', 'https://www.reddit.com/r/bangtan/comments/q1xo77', 'community_archive', 4, '2021-10-05', '2026-08-10', 'Contemporaneous archive links directly to the official BTS_twt post and identifies the pictured book area as RM’s bookshelf.'),
  ('src-weverse-korean-art-rm', 'Getting to know Korean modern and contemporary art with RM', 'Weverse Magazine', 'https://magazine.weverse.io/article/view/120?artist=BTS&lang=en', 'official_content', 2, '2021-03-24', '2026-08-10', 'Official feature says RM had been reading The Depth of Landscape and explains the book’s connection to Kang Yobae’s art.'),
  ('src-weverse-rm-20201004-recommendations', 'RM book, documentary and song post', 'Weverse', 'https://weverse.io/bts/artist/1640184234924405', 'rm_direct', 1, '2020-10-04', '2026-08-10', 'Legacy primary URL recovered from the contemporaneous r/bangtan weekly archive. The current page requires community login, so its wording could not be rechecked in this session.'),
  ('src-koreaboo-depth-landscape', 'RM’s latest book, film and song recommendations', 'Koreaboo', 'https://www.koreaboo.com/news/bts-rm-latest-book-film-song-recommendations/', 'reputable_secondary', 3, '2020-10-03', '2026-08-10', 'Contemporaneous article reproduces the Weverse images and attributes an explicit recommendation of the book, documentary and song to RM.'),
  ('src-reddit-weekly-20201004', 'Weekly Round-Up: September 28th–October 4th', 'r/bangtan', 'https://www.reddit.com/r/bangtan/comments/j5032t', 'community_archive', 4, '2020-10-04', '2026-08-10', 'Contemporaneous index preserves the exact legacy Weverse URL for RM’s 2020-10-04 post.'),
  ('src-daegu-museum-instagram-rm-kang', 'RM visit and Kang Yobae work', 'Daegu Art Museum', 'https://www.instagram.com/p/CWCNRdyvJDA/', 'institutional_record', 2, '2021-11-08', '2026-08-10', 'The museum states that RM visited its exhibitions and posted a verification photo with Kang Yobae’s Munnamu (2020).'),
  ('src-artbava-kang-carnation', 'Kang Yobae: Carnation — When Mind Becomes Body', 'ARTBAVA', 'https://www.artbava.com/exhibits/%EA%B0%95%EC%9A%94%EB%B0%B0-%EC%B9%B4%EB%84%A4%EC%9D%B4%EC%85%98-%EB%A7%88%EC%9D%8C%EC%9D%B4-%EB%AA%B8%EC%9D%B4-%EB%90%A0-%EB%95%8C', 'reputable_secondary', 3, NULL, '2026-08-10', 'Exhibition title, venue, dates and award context.'),
  ('src-daegu-museum-kang-video', 'Kang Yobae: Carnation — When Mind Becomes Body', 'Daegu Art Museum / YouTube', 'https://www.youtube.com/watch?v=qCG8cS9RW3E', 'official_content', 2, NULL, '2026-08-10', 'Official museum video documents the exhibition and its scope.');

INSERT OR IGNORE INTO claims
  (id, subject_entity_id, object_entity_id, relation_type, evidence_level, evidence_origin, verification_status, claim_text, event_date, publication_ready, notes)
VALUES
  ('claim-rm-depth-landscape', 'rm', 'book-depth-of-the-landscape', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes The Depth of the Landscape among books RM had recently mentioned.', NULL, 1, 'Do not upgrade to read or recommended without the underlying primary moment.'),
  ('claim-rm-honeybees', 'rm', 'book-honeybees-distant-thunder', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes Mitsubachi to Enrai among books RM had recently mentioned.', NULL, 1, 'Use the English title as the display title and preserve the original title.'),
  ('claim-rm-that-summers-end', 'rm', 'book-that-summers-end', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes That Summer’s End among books RM had recently mentioned.', '2022-09', 1, 'A secondary report further ties the book to an RM Instagram Story.'),
  ('claim-rm-all-about-saul-leiter', 'rm', 'book-all-about-saul-leiter', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes All About Saul Leiter among books RM had recently mentioned.', NULL, 1, 'No recommendation claim is supported by the current source.'),
  ('claim-rm-midnight-library', 'rm', 'book-midnight-library', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes The Midnight Library among books RM had recently mentioned.', NULL, 1, 'The exact In the SOOP 2 episode and timestamp remain a separate research task.'),
  ('claim-rm-doing-good-better', 'rm', 'book-doing-good-better', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Weverse includes Doing Good Better among books RM had recently mentioned.', NULL, 1, 'No recommendation claim is supported by the current source.'),
  ('claim-rm-midnight-library-read', 'rm', 'book-midnight-library', 'read', 'confirmed', 'public_observation', 'corroborated', 'Multiple independent recaps identify RM reading The Midnight Library during In the SOOP BTS ver. Season 2, especially episode 3.', '2021-10-29', 0, 'High-confidence research finding, but keep it out of the publication queue until the official episode timestamp or a licensed clip is checked.'),
  ('claim-rm-doing-good-better-shelf', 'rm', 'book-doing-good-better', 'mentioned', 'mentioned', 'community_identification', 'corroborated', 'A staff-curated library list identifies Doing Good Better among the books visible in RM’s official BTS account photo from 2021-10-05.', '2021-10-05', 0, 'The original post and photograph are verified. Keep this dated observation out of the publication queue until the exact spine is independently matched against a known edition.'),
  ('claim-rm-depth-landscape-read', 'rm', 'book-depth-of-the-landscape', 'read', 'confirmed', 'official_summary', 'verified', 'Weverse Magazine states that RM had been reading The Depth of Landscape.', '2020-10', 1, 'This safely upgrades the relationship from mentioned to read.'),
  ('claim-rm-depth-landscape-recommended', 'rm', 'book-depth-of-the-landscape', 'recommended', 'confirmed', 'direct_statement', 'open_lead', 'A contemporaneous article attributes an explicit recommendation of The Depth of Landscape to RM’s 2020-10-04 Weverse post.', '2020-10-04', 0, 'The exact primary URL is known, but the post wording still needs to be rechecked in an authenticated Weverse session.'),
  ('claim-rm-kang-yobae-mentioned', 'rm', 'artist-kang-yobae', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Official sources connect RM to Kang Yobae through the artist’s book and a photographed museum visit.', '2021-11', 1, 'Do not upgrade to admired without a direct evaluative statement from RM.'),
  ('claim-rm-daegu-art-museum-visited', 'rm', 'museum-daegu-art-museum', 'visited', 'confirmed', 'official_summary', 'verified', 'Daegu Art Museum states that RM visited its exhibitions.', '2021-11', 1, 'The museum post is dated 2021-11-08; the exact visit date is not stated.'),
  ('claim-rm-kang-carnation-visited', 'rm', 'exhibition-kang-yobae-carnation', 'visited', 'confirmed', 'official_summary', 'verified', 'Daegu Art Museum states that RM visited its exhibitions and photographed a work in Kang Yobae’s active solo exhibition.', '2021-11', 1, 'The exhibition was open from 2021-10-13 through 2022-01-09.'),
  ('claim-rm-munnamu-mentioned', 'rm', 'artwork-kang-yobae-munnamu', 'mentioned', 'mentioned', 'official_summary', 'verified', 'Daegu Art Museum identifies Kang Yobae’s Munnamu (2020) as the work in RM’s posted verification photo.', '2021-11', 1, 'Visibility supports mentioned, not collected or owned.'),
  ('claim-munnamu-created-by-kang', 'artwork-kang-yobae-munnamu', 'artist-kang-yobae', 'created_by', 'confirmed', 'official_summary', 'verified', 'Munnamu was created by Kang Yobae in 2020.', '2020', 1, NULL),
  ('claim-depth-landscape-created-by-kang', 'book-depth-of-the-landscape', 'artist-kang-yobae', 'created_by', 'confirmed', 'official_summary', 'verified', 'The Depth of the Landscape collects Kang Yobae’s writing and artwork.', NULL, 1, 'The book is both a literary object and a bridge into the artist’s visual practice.'),
  ('claim-kang-exhibition-held-at-daegu', 'exhibition-kang-yobae-carnation', 'museum-daegu-art-museum', 'held_at', 'confirmed', 'official_summary', 'verified', 'Kang Yobae: Carnation — When Mind Becomes Body was held at Daegu Art Museum.', '2021-10-13', 1, NULL),
  ('claim-munnamu-shown-at-kang-exhibition', 'artwork-kang-yobae-munnamu', 'exhibition-kang-yobae-carnation', 'shown_at', 'confirmed', 'official_summary', 'verified', 'Munnamu was shown in Kang Yobae’s Daegu Art Museum exhibition.', '2021', 1, 'The museum’s RM visit post identifies the work within the active exhibition context.');

INSERT OR IGNORE INTO claim_sources
  (claim_id, source_id, evidence_role, locator, evidence_note, checked_at)
VALUES
  ('claim-rm-depth-landscape', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the book as a recent mention.', '2026-08-10'),
  ('claim-rm-depth-landscape', 'src-hanbooks-depth-landscape', 'context', 'Product metadata', 'Confirms the author, Korean title and ISBN; it does not support the RM relationship.', '2026-08-10'),
  ('claim-rm-honeybees', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the romanized Japanese title as a recent mention.', '2026-08-10'),
  ('claim-rm-honeybees', 'src-penguin-honeybees-sample', 'context', 'Copyright page', 'Confirms the English title, original Japanese title and author.', '2026-08-10'),
  ('claim-rm-that-summers-end', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the Korean poetry collection as a recent mention.', '2026-08-10'),
  ('claim-rm-that-summers-end', 'src-hankyung-that-summers-end', 'corroborates', 'Article body and reproduced Instagram Story image', 'Reports the cover appearing in RM’s Instagram Story and identifies the author and collection.', '2026-08-10'),
  ('claim-rm-all-about-saul-leiter', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the book as a recent mention.', '2026-08-10'),
  ('claim-rm-all-about-saul-leiter', 'src-thames-all-about-saul-leiter', 'context', 'Publisher details', 'Confirms title, contributors and edition metadata.', '2026-08-10'),
  ('claim-rm-midnight-library', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the book as a recent mention.', '2026-08-10'),
  ('claim-rm-midnight-library', 'src-prh-midnight-library', 'context', 'Publisher metadata', 'Confirms title, author and publication details.', '2026-08-10'),
  ('claim-rm-doing-good-better', 'src-weverse-bibilly-hills', 'supports', 'Reading section; list of recently mentioned books', 'The official feature names the book as a recent mention.', '2026-08-10'),
  ('claim-rm-doing-good-better', 'src-prh-doing-good-better', 'context', 'Publisher metadata', 'Confirms title, author and publication details.', '2026-08-10'),
  ('claim-rm-doing-good-better-shelf', 'src-bts-twitter-20211005-green', 'supports', 'Photo 1; posted 2021-10-05 at 16:35', 'The official post supplies the primary bookshelf photograph, but its caption does not name the book.', '2026-08-10'),
  ('claim-rm-doing-good-better-shelf', 'src-vpl-namjoon-bookshelf', 'corroborates', 'Doing Good Better entry', 'The staff-curated list identifies the title in RM’s 2021-10-05 bookshelf image; its platform label conflicts with the verified Twitter URL.', '2026-08-10'),
  ('claim-rm-doing-good-better-shelf', 'src-reddit-rm-20211005', 'context', 'Original submission URL and contemporaneous bookshelf discussion', 'The archived thread resolves the original source to the official BTS_twt post and confirms viewers recognized the image as RM’s bookshelf.', '2026-08-10'),
  ('claim-rm-depth-landscape-read', 'src-weverse-korean-art-rm', 'supports', 'Kang Yobae section', 'The official feature explicitly describes the book as one RM had been reading recently.', '2026-08-10'),
  ('claim-rm-depth-landscape-read', 'src-weverse-bibilly-hills', 'corroborates', 'Reading section', 'The later official feature again includes the book among RM’s recent mentions.', '2026-08-10'),
  ('claim-rm-depth-landscape-recommended', 'src-koreaboo-depth-landscape', 'supports', 'Reproduced 2020-10-04 Weverse post and translation', 'The article attributes an explicit recommendation to RM and reproduces the source images.', '2026-08-10'),
  ('claim-rm-depth-landscape-recommended', 'src-weverse-rm-20201004-recommendations', 'context', 'Legacy RM artist post', 'The primary URL is preserved, but its content currently requires an authenticated community session to inspect.', '2026-08-10'),
  ('claim-rm-depth-landscape-recommended', 'src-reddit-weekly-20201004', 'context', 'Official SNS table: 201004 Weverse — Namjoon', 'The contemporaneous archive resolves the exact primary URL and date.', '2026-08-10'),
  ('claim-rm-kang-yobae-mentioned', 'src-weverse-korean-art-rm', 'supports', 'Kang Yobae section', 'The official feature connects RM’s reading directly to Kang Yobae’s life and art.', '2026-08-10'),
  ('claim-rm-kang-yobae-mentioned', 'src-daegu-museum-instagram-rm-kang', 'corroborates', 'Museum caption', 'The museum states that RM posted a verification photo with Kang Yobae’s work.', '2026-08-10'),
  ('claim-rm-daegu-art-museum-visited', 'src-daegu-museum-instagram-rm-kang', 'supports', 'Museum caption dated 2021-11-08', 'The institution directly states that RM visited its exhibitions.', '2026-08-10'),
  ('claim-rm-kang-carnation-visited', 'src-daegu-museum-instagram-rm-kang', 'supports', 'Caption and exhibition hashtags', 'The museum connects RM’s visit and photo to Kang Yobae’s work and the active exhibition.', '2026-08-10'),
  ('claim-rm-kang-carnation-visited', 'src-artbava-kang-carnation', 'context', 'Exhibition listing', 'Confirms title, venue and dates.', '2026-08-10'),
  ('claim-rm-munnamu-mentioned', 'src-daegu-museum-instagram-rm-kang', 'supports', 'Museum caption and image', 'The museum identifies the photographed work as Munnamu (2020).', '2026-08-10'),
  ('claim-munnamu-created-by-kang', 'src-daegu-museum-instagram-rm-kang', 'supports', 'Artwork credit in caption', 'The museum credits Kang Yobae and supplies title, year, medium and dimensions.', '2026-08-10'),
  ('claim-depth-landscape-created-by-kang', 'src-weverse-korean-art-rm', 'supports', 'Kang Yobae section', 'The official feature describes the volume as a compilation of Kang’s art and personal writings.', '2026-08-10'),
  ('claim-depth-landscape-created-by-kang', 'src-hanbooks-depth-landscape', 'corroborates', 'Book metadata and description', 'The bookseller credits Kang Yobae and describes the volume as his collection of writing, paintings and thought.', '2026-08-10'),
  ('claim-kang-exhibition-held-at-daegu', 'src-artbava-kang-carnation', 'supports', 'Exhibition listing', 'Confirms the exhibition was held at Daegu Art Museum.', '2026-08-10'),
  ('claim-kang-exhibition-held-at-daegu', 'src-daegu-museum-kang-video', 'corroborates', 'Official exhibition video', 'The museum’s video independently documents the exhibition.', '2026-08-10'),
  ('claim-munnamu-shown-at-kang-exhibition', 'src-daegu-museum-instagram-rm-kang', 'supports', 'Museum caption during the exhibition run', 'The institution identifies the work in RM’s exhibition visit context.', '2026-08-10'),
  ('claim-munnamu-shown-at-kang-exhibition', 'src-artbava-kang-carnation', 'context', 'Exhibition dates and venue', 'Confirms the exhibition was active when the museum posted about RM’s visit.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-rkive-read-with-bts', 'supports', 'In the SOOP 2: episode 1 TBR mention; episode 3 reading', 'The fan research provides the most specific episode-level sequence currently found.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-reddit-its2-ep3', 'corroborates', 'Episode 3 discussion dated 2021-10-29', 'A contemporaneous viewer independently notes RM reading the identified book.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-elcomercio-its2-ep3', 'corroborates', 'Embedded episode 3 social post', 'A secondary report embeds a contemporary post showing RM and SUGA reading during episode 3.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-buro-midnight-library', 'corroborates', 'The Midnight Library section', 'The article says RM was reading the book and narrated a passage, but lacks a timestamp.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-ameblo-midnight-library-highlight', 'corroborates', 'In the SOOP 2 scene; episode and timestamp not supplied', 'The post identifies a passage RM highlighted in the book; the archived text is not treated as a substitute for checking the licensed episode.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-weverse-in-the-soop2-guide', 'context', 'Season 2 release schedule', 'Confirms the official programme and episode release dates but not the book-specific scene.', '2026-08-10');

INSERT OR IGNORE INTO claim_discovery_credits
  (claim_id, source_id, discovery_role, locator, credit_note, checked_at)
VALUES
  ('claim-rm-midnight-library-read', 'src-rkive-read-with-bts', 'identified', 'In the SOOP 2 table: episode 1 TBR mention; episode 3 reading', 'This archive supplied the most specific episode sequence used to frame the primary-source check.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-reddit-its2-ep3', 'independently_identified', 'Episode 3 discussion dated 2021-10-29', 'Contemporaneous viewers independently identified RM reading the title in episode 3.', '2026-08-10'),
  ('claim-rm-midnight-library-read', 'src-ameblo-midnight-library-highlight', 'identified', 'Highlighted-passage post', 'This fan record identified the passage associated with the later episode scene.', '2026-08-10'),
  ('claim-rm-doing-good-better-shelf', 'src-vpl-namjoon-bookshelf', 'identified', 'Doing Good Better entry', 'Vancouver Public Library preserved the title identification and linked it to the dated bookshelf photograph.', '2026-08-10'),
  ('claim-rm-doing-good-better-shelf', 'src-reddit-rm-20211005', 'preserved', 'Original submission URL', 'The contemporaneous thread preserves the official BTS_twt URL and the date of the bookshelf post.', '2026-08-10'),
  ('claim-rm-depth-landscape-recommended', 'src-reddit-weekly-20201004', 'preserved', 'Official SNS table: 201004 Weverse — Namjoon', 'The weekly archive preserves the exact legacy Weverse URL needed for the unresolved primary check.', '2026-08-10');

INSERT OR IGNORE INTO research_leads
  (id, domain, lead_text, proposed_entity_title, proposed_relation_type, discovery_origin, source_url, source_locator, status, notes)
VALUES
  ('lead-midnight-library-in-the-soop2', 'literature', 'Locate the exact In the SOOP BTS ver. Season 2 scene showing or discussing The Midnight Library.', 'The Midnight Library', 'mentioned', 'community_identification', 'https://weverse.io/bts/notice/1720', 'Episode and timestamp not yet verified', 'verifying', 'Record episode, timestamp, visible cover or spoken wording. Do not infer recommendation from visibility alone.'),
  ('lead-in-the-soop2-quote-identification', 'literature', 'Identify the book behind a quotation used or read during In the SOOP BTS ver. Season 2.', NULL, 'mentioned', 'community_identification', 'https://namjoonsbooklist.com/', 'Community archive lead; primary locator required', 'new', 'Match the quotation against an edition, then verify it against the official episode with a timestamp.'),
  ('lead-midnight-library-recommendation', 'literature', 'Verify the claim that RM recommended The Midnight Library to V during In the SOOP 2.', 'The Midnight Library', 'recommended', 'community_identification', 'https://www.gqindia.com/content/gq-reads-5-books-recommended-by-rm-that-flaunt-the-bts-leaders-lyrical-prowess', 'Exact episode, dialogue and timestamp not supplied', 'verifying', 'Do not publish recommended until the official dialogue is checked. Existing evidence safely supports mentioned and strongly suggests read.'),
  ('lead-midnight-library-product-placement', 'literature', 'Determine whether The Midnight Library exposure in In the SOOP 2 was sponsored product placement.', 'The Midnight Library', 'mentioned', 'community_identification', 'https://www.reddit.com/r/bangtan/comments/qsanxa', 'Episode 5 discussion; no authoritative sponsorship record found', 'parked', 'Community discussion notes repeated clear exposure and audiobook use, but this remains speculation without production credits, sponsor disclosure or publisher confirmation.'),
  ('lead-doing-good-better-spine-match', 'literature', 'Independently match the Doing Good Better spine in RM’s 2021-10-05 bookshelf photograph to a known edition.', 'Doing Good Better', 'mentioned', 'community_identification', 'https://x.com/BTS_twt/status/1445397240118382592', 'Photo 1; lower book area', 'verifying', 'The primary post and date are confirmed. Vancouver Public Library identifies the title, but the archive still needs a reproducible visual locator or edition match before publishing this dated observation.'),
  ('lead-doing-good-better-read-or-recommended', 'literature', 'Find a direct statement or unambiguous scene showing whether RM read or recommended Doing Good Better.', 'Doing Good Better', 'read', 'official_summary', 'https://magazine.weverse.io/article/view/632?artist=BTS&lang=en', 'Reading section names only a recent mention', 'parked', 'No direct reading or recommendation evidence was found in this research pass. Do not infer either action from the bookshelf image.'),
  ('lead-depth-landscape-primary-recommendation', 'literature', 'Recheck the wording and images in RM’s 2020-10-04 Weverse post to verify an explicit recommendation of The Depth of Landscape.', 'The Depth of the Landscape', 'recommended', 'direct_statement', 'https://weverse.io/bts/artist/1640184234924405', 'Legacy RM artist post; login required', 'verifying', 'The exact primary URL and date are established. A contemporaneous article reproduces the post and says RM explicitly recommended the selections, but publication waits for a direct authenticated check.');

UPDATE research_leads
SET proposed_entity_title = 'The Midnight Library',
    source_url = 'https://www.reddit.com/r/bangtan/comments/qnama0',
    source_locator = 'In the SOOP 2 episode 4; exact timestamp pending',
    status = 'verifying',
    notes = 'A contemporaneous episode discussion attributes the shared quotation to The Midnight Library. Verify the exact wording and timestamp against the official episode.',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'lead-in-the-soop2-quote-identification';

UPDATE claims
SET notes = 'A separate verified claim now supports read. The explicit recommendation remains an open primary-source check.',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'claim-rm-depth-landscape';

UPDATE research_leads
SET proposed_relation_type = 'read',
    source_locator = 'Episode 1: TBR mention; episode 3: reading; exact timestamps pending. Authenticated Weverse check on 2026-08-10 found no accessible purchased VOD in the current session.',
    notes = 'Multiple independent sources converge on episode 3. The official Weverse library was checked lawfully, but the paid season was unavailable in the current session; no access controls were bypassed. Record the official timestamp or licensed clip before promoting the stronger read claim to publication-ready.',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'lead-midnight-library-in-the-soop2';

UPDATE research_leads
SET source_locator = 'In the SOOP 2 episode 4; exact timestamp pending. A community archive also identifies the highlighted passage.',
    notes = 'A contemporaneous episode discussion and a separate fan archive attribute the shared or highlighted passage to The Midnight Library. The official paid VOD was unavailable in the authenticated session checked on 2026-08-10, so exact wording and timestamp remain unverified.',
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'lead-in-the-soop2-quote-identification';
